### Configuration file! ##

stats-debug: true
firebase-storage-type: firestore
firebase-realtime-url: "https://DATABASE_NAME.firebaseio.com"
firebase-credentials-location: "src/main/resources/firebaseCredentials.json"

## Data Storage Configurations ##

# Firestore #
firebase-data-collection: 'scoutingData'

## Authentication Configurations ##
spring:
  datasource:
    url: jdbc:h2:C:/users/ianta/Desktop/tech-stuff/userDB/test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      hbm2dll:
        auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data